[package]
name = "gluon_format"
version = "0.6.2" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "Code formatting for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

[dependencies]
log = "0.3.6"
pretty = "0.3.2"
itertools = "0.5.6"

gluon_base = { path = "../base", version = "0.6.2" } # GLUON
gluon_parser = { path = "../parser", version = "0.6.2" } # GLUON

[dev-dependencies]
env_logger = "0.3.4"
difference = "1.0"
pretty_assertions = "0.4"

[features]
test = []
