[package]
name = "gluon_repl"
version = "0.6.2" # GLUON
authors = ["Markus Westerlind <marwes91@gmail.com>"]

license = "MIT"
description = "REPL for gluon. A static, type inferred programming language for application embedding"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon_repl"

[[bin]]
name = "gluon"
path = "src/main.rs"
doc = false

[dependencies]

gluon = { version = "0.6.2", path = ".." } # GLUON
gluon_vm = { version = "0.6.2", path = "../vm" } # GLUON
gluon_completion = { path = "../completion", version = "0.6.2" } # GLUON
gluon_format = { version = "0.6.2", path = "../format" } # GLUON

futures = "0.1.11"
clap = "2.22.0"
log = "0.3.6"
env_logger = { version = "0.3.4", optional = true }
lazy_static = "0.2.0"
rustyline = "1.0.0"
walkdir = "1"

[dev-dependencies]
pretty_assertions = "0.4"

[features]
default = ["env_logger"]
