[package]
name = "gluon_parser"
version = "0.6.2" # GLUON
authors = ["Markus <marwes91@gmail.com>"]

license = "MIT"

description = "The parser for the gluon programming language"

repository = "https://github.com/gluon-lang/gluon"
documentation = "https://docs.rs/gluon"

build = "build.rs"

[dependencies]
collect-mac = "0.1.0"
env_logger = { version = "0.3.4", optional = true }
itertools = "0.6.0"
quick-error = "1.0.0"
lalrpop-util = "0.13.1"
log = "0.3.6"
pretty = "0.3.2"
gluon_base = { path = "../base", version = "0.6.2" } # GLUON

[dev-dependencies]
difference = "1.0"
pretty_assertions = "0.4"

[build-dependencies]
lalrpop = "0.13.1"

[features]
test = ["env_logger"]
